version: '3.8'
services:
  ssa-mysql:
    platform: linux/x86_64
    image: mysql:5.7.40
    container_name: ssa-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=Analytics